# Generated by Django 4.2.14 on 2024-07-29 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_hazardtype_hazardname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazardname',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.hazardtype'),
        ),
    ]
