# Generated by Django 3.2.23 on 2024-08-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0004_subactivity_trucktype"),
    ]

    operations = [
        migrations.AddField(
            model_name="debristype",
            name="rate_matrix_fields",
            field=models.JSONField(blank=True, null=True),
        ),
    ]