# Generated by Django 4.2.14 on 2024-08-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debristype',
            options={'permissions': [('can_manage_debris_type', 'Can manage debris type')]},
        ),
        migrations.AlterModelOptions(
            name='hazardname',
            options={'permissions': [('can_manage_hazard_name', 'Can manage hazard name')]},
        ),
        migrations.AlterModelOptions(
            name='hazardtype',
            options={'permissions': [('can_manage_hazard_type', 'Can manage hazard type')]},
        ),
        migrations.AlterModelOptions(
            name='subactivity',
            options={'permissions': [('can_manage_sub_activity', 'Can manage sub activity')]},
        ),
        migrations.AlterModelOptions(
            name='trucktype',
            options={'permissions': [('can_manage_truck_description', 'Can manage truck description')]},
        ),
    ]
