# Generated by Django 3.2.23 on 2024-08-06 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0007_contractorratematrix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractorratematrix",
            name="reduction_rate",
            field=models.FloatField(
                blank=True,
                default=0,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
