# Generated by Django 3.2.23 on 2024-08-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_auto_20240808_1103'),
        ('ticketing', '0008_alter_contractorratematrix_reduction_rate'),
    ]

    operations = [
    ]
