# Generated by Django 4.2.14 on 2024-08-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_alter_debristype_options_alter_hazardname_options_and_more'),
        ('ticketing', '0008_alter_contractorratematrix_reduction_rate'),
    ]

    operations = [
    ]
