# Generated by Django 3.2.23 on 2024-08-09 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0008_alter_contractorratematrix_reduction_rate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="debristype",
            options={"permissions": [("manage_debris_type", "Manage Debris Type")]},
        ),
        migrations.AlterModelOptions(
            name="hazardname",
            options={"permissions": [("manage_hazard_name", "Manage Hazard Name")]},
        ),
        migrations.AlterModelOptions(
            name="hazardtype",
            options={"permissions": [("manage_hazard_type", "Manage Hazard Type")]},
        ),
        migrations.AlterModelOptions(
            name="subactivity",
            options={"permissions": [("manage_subactivity", "Manage SubActivity")]},
        ),
        migrations.AlterModelOptions(
            name="trucktype",
            options={"permissions": [("manage_truck_type", "Manage Truck Type")]},
        ),
    ]
