# Generated by Django 3.2.23 on 2024-08-09 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0009_auto_20240809_0540"),
        ("ticketing", "0010_auto_20240808_1314"),
    ]

    operations = []
