# Generated by Django 3.2.23 on 2024-08-09 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
        ("ticketing", "0011_merge_0009_auto_20240809_0540_0010_auto_20240808_1314"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractorratematrix",
            name="debris_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="debris_rate_matrix",
                to="administration.debristype",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="sub_activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="administration.subactivity",
            ),
        ),
    ]
