# Generated by Django 3.2.23 on 2024-07-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240723_0537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
