# Generated by Django 3.2.23 on 2024-07-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20240725_1707"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="device_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
