# Generated by Django 3.2.23 on 2024-07-30 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prime_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_prime_contractor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserAdditionalData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='useradditionaldata',
            constraint=models.UniqueConstraint(fields=('company_name',), name='unique_company_name'),
        ),
        migrations.AddConstraint(
            model_name='useradditionaldata',
            constraint=models.UniqueConstraint(fields=('prefix',), name='unique_prefix'),
        ),
    ]
