# Generated by Django 3.2.23 on 2024-08-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_useradditionaldata_email_ticket_receipt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("device_id",), name="unique_device_id"
            ),
        ),
    ]
