# Generated by Django 4.2.14 on 2024-08-06 08:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20240805_0705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'permissions': [('can_manage_position', 'Can manage position')]},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('can_manage_role', 'Can manage role')]},
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='role',
            name='role_permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
