# Generated by Django 3.2.23 on 2024-08-09 05:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0010_userattachments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={"permissions": [("manage_position", "Manage Position")]},
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"permissions": [("manage_role", "Manage Role")]},
        ),
        migrations.AddField(
            model_name="role",
            name="role_permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.CreateModel(
            name="CustomUserPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_type",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("web", "Web"),
                            ("both", "Both"),
                        ],
                        default="web",
                        max_length=50,
                    ),
                ),
                (
                    "group_name",
                    models.CharField(
                        choices=[
                            ("Administration", "Administration"),
                            ("Event", "Event"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "permission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
            ],
        ),
    ]
