# Generated by Django 4.2.14 on 2024-08-07 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_position_options_alter_role_options_and_more'),
        ('users', '0010_userattachments'),
    ]

    operations = [
    ]
